### ISSUE TITLE
Colors codes

### ISSUE THREAD

**Issue by manumora** [alfonsrv/printer-monitoring#2]
Are you sure oid colors are fine? Comparing the results with my Xerox dashboard I see that cyan and yellow are exchanged, I mean, cyan oid code finishes in 4 and yellow in 2. So correct ones are:

    oid_cyan_toner_name = '1.3.6.1.2.1.43.11.1.1.6.1.4'
    oid_cyan_toner_capacity = '1.3.6.1.2.1.43.11.1.1.8.1.4'
    oid_cyan_toner_remaining = '1.3.6.1.2.1.43.11.1.1.9.1.4'

    oid_yellow_toner_name = '1.3.6.1.2.1.43.11.1.1.6.1.2'
    oid_yellow_toner_capacity = '1.3.6.1.2.1.43.11.1.1.8.1.2'
    oid_yellow_toner_remaining = '1.3.6.1.2.1.43.11.1.1.9.1.2'

Good job. Thank you!

**Comment by alfonsrv** [comment]
Hello @manumora, really depends on your printer. Which Xerox do you have and which `variant` are you using?
